"""Build the processed dataset from the raw CSV.

Run from the repo root:

    python scripts/prepare_data.py

Outputs (both git-ignored, both regenerated by this script):

- ``data/processed/sessions_clean.parquet`` - all 1,320 rows, canonical column names,
  engineered features and per-row validation flags. Missing values are kept as ``NaN``;
  downstream model prep filters rows and imputes per task.
- ``data/processed/validation_report.json`` - counts and percentages for every
  data-quality rule.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

# Work whether or not the package has been `pip install -e .`-ed.
_SRC = Path(__file__).resolve().parents[1] / "src"
if _SRC.is_dir() and str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from evcharging.config import CLEAN_PARQUET, PROCESSED_DIR, VALIDATION_REPORT
from evcharging.data import add_validation_flags, load_raw, write_validation_report
from evcharging.features import build_features


def main() -> None:
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

    df = load_raw()
    print(f"loaded {len(df):,} rows, {df.shape[1]} columns")

    df = build_features(df)
    df = add_validation_flags(df)
    print(f"built features -> {df.shape[1]} columns")

    report = write_validation_report(df, VALIDATION_REPORT)
    print(
        f"validation: {report['n_rows_flagged']:,} / {report['n_rows']:,} rows "
        f"({report['pct_rows_flagged']}%) violate at least one rule"
    )
    print(json.dumps(report["rules"], indent=2))

    df.to_parquet(CLEAN_PARQUET, index=False)
    print(f"wrote {CLEAN_PARQUET.relative_to(CLEAN_PARQUET.parents[2])}")
    print(f"wrote {VALIDATION_REPORT.relative_to(VALIDATION_REPORT.parents[2])}")


if __name__ == "__main__":
    main()
